sudo: required
services : 
  - docker

before-install:
  - docker build -t mithileshcheliyan/docker-react -f Dockerfile.dev .

script:
#  - docker run mithileshcheliyan/docker-react npm run test -- --coverage
  - docker run -e CI=true mithileshcheliyan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app:  "docker-react"
  env:  "Dockerreact-env"
  bucket_name:  "elasticbeanstalk-us-east-2-856054011331"
  bucket_path:  "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY

  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY

#secure: "$AWS_SECURE_KEY"


#access_key_id: $AWS_ACCESS_KEY
#secret_acces_key: $AWS_SECRET_KEY
