sudo: required
services : 
  - docker

before-install:
  - docker build -t mithileshcheliyan/docker-react -f Dockerfile.dev

script:
  - docker run mithileshcheliyan/docker-react npm run test -- -- coverage
  